spring:
  application:
    name: ternary-operator

    # database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TaskFlow
    username: root
    password: 12345678

#jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

#jwt
jwt:
  secret:
    key: aognijodsbnmlzxvcmnonaowngfonasonvlscamnklvasdfaweahbnfgjfggzsgffsbxvbdsg

  access-token-expiration: 3600000